# Generated by Django 4.2.7 on 2024-04-29 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Diary", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diaryentry", old_name="user", new_name="created_by",
        ),
        migrations.RenameField(
            model_name="diaryentry", old_name="date_posted", new_name="created_on",
        ),
    ]
